services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    networks:
      - prowlarr-stremio
    restart: unless-stopped

  prowlarr-stremio:
    build: .
    environment:
      - PROWLARR_URL=${PROWLARR_URL}
      - PROWLARR_API_KEY=${PROWLARR_API_KEY}
      - REAL_DEBRID_API_TOKEN=${REAL_DEBRID_API_TOKEN}
    ports:
      - 7000:7000
    depends_on:
      - prowlarr
    networks:
      - prowlarr-stremio
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - prowlarr-config:/config
    networks:
      - prowlarr-stremio
    ports:
      - 9696:9696
    restart: unless-stopped

networks:
  prowlarr-stremio:

volumes:
  prowlarr-config:
