services:
  prowlarr-stremio:
    build: .
    environment:
      - PROWLARR_URL=${PROWLARR_URL:-"http://prowlarr:9696"}
      - PROWLARR_API_KEY=${PROWLARR_API_KEY}
      - PRODUCTION=false
    ports:
      - 7000:7000
    depends_on:
      - prowlarr
    networks:
      - prowlarr-stremio
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - prowlarr-config:/config
    networks:
      - prowlarr-stremio
    ports:
      - 9696:9696
    restart: unless-stopped

  cloudflared: 
    image: cloudflare/cloudflared
    restart: unless-stopped 
    command: tunnel run --token="${CLOUD_FLARE_TUNNEL_TOKEN}"
    networks:
      - prowlarr-stremio

networks:
  prowlarr-stremio:

volumes:
  prowlarr-config:
