services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    networks:
      - jackett-stremio
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    environment:
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    depends_on:
      - flaresolverr
    networks:
      - jackett-stremio
    ports:
      - 9117:9117
    restart: unless-stopped
    volumes:
      - jackett-config:/config
      - jackett-downloads:/downloads

  jackett-stremio:
    build: .
    environment:
      - JACKETT_URL=${JACKETT_URL}
      - JACKETT_API_KEY=${JACKETT_API_KEY}
      - REAL_DEBRID_API_TOKEN=${REAL_DEBRID_API_TOKEN}
    ports:
      - 7000:7000
    depends_on:
      - jackett
    networks:
      - jackett-stremio
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./

networks:
  jackett-stremio:

volumes:
  jackett-config:
  jackett-downloads:
